source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Franz_Example', :exclusive => true do
  pod "Franz", :path => "../"
end

target 'Franz_Tests', :exclusive => true do
  pod "Franz", :path => "../"

  pod 'FBSnapshotTestCase'
end
