source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Franz_Example' do
  pod "Franz", :path => "../"
end

target 'Franz_Tests' do
  pod "Franz", :path => "../"

  pod 'FBSnapshotTestCase'
end
